// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SearchTest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SearchTest', async function() {
    await driver.get("https://www.google.com")
    await driver.manage().window().setRect(1024, 768)
    await driver.findElement(By.name("q")).sendKeys("seleniumhq documentation")
    await driver.findElement(By.name("q")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".g:nth-child(1) > div:nth-child(2) .LC20lb")).click()
  })
})
